stages:
  - mirror

push-mirror:
  stage: mirror
  script:
    - git clone --mirror git@git.teaspotstudio.ru:aerospace/minetest.git
    - cd minetest.git
    - git push --mirror git@github.com:Teaspot-Studio/minetest.git
    - cd .. && rm -rf minetest.git
